import React, { createContext, useContext, useState, useEffect } from 'react';

const dictionary = {
  en: {
    siteTitle: "Shale-Namma Pride",
    heroBadge: "Official Parents Portal",
    heroTitle: "Live School Updates for Every Parent",
    heroSubtitle: "Easily stay connected with your child's school. See today's meals, student achievements, and important notices.",
    valTransparency: "Transparency",
    valSafety: "Safety",
    valAchievement: "Achievement",
    valCommunication: "Communication",
    dailyMealProgram: "Today's School Meals",
    mealFeedSubtitle: "See what your child is eating at school today. We ensure fresh and healthy food for every student.",
    mealPrepTitle: "Lunch is being served",
    mealPrepDesc: "Please wait while we update today's meal information.",
    todaySpecial: "Today's Special",
    pastRecord: "Past Record",
    menuItems: "MENU ITEMS",
    infraTitle: "Our Facilities",
    infraSubtitle: "We provide a nurturing environment with state-of-the-art facilities to ensure holistic development.",
    exploreGallery: "Explore Gallery",
    starsStageSet: "The Stage is Set",
    starsStageDesc: "Stay tuned as we prepare to celebrate our first set of high achievers in the grand hall of fame.",
    searchCirculars: "Search circulars...",
    filterAll: "All",
    filterUrgent: "Urgent",
    filterImportant: "Important",
    filterInfo: "Info",
    viewUpdates: "View Updates",
    parentsPortal: "Parents Portal",
    adminOnline: "Admin Online",
    adminOffline: "Admin Offline",
    adminTyping: "Administration is typing a response...",
    liveSyncText: "LIVE SYNC",
    liveSyncActive: "Live Sync Active",
    attachImage: "Attach Image",
    midDayMeals: "Mid-Day Meals",
    noMealsTitle: "No meals posted yet",
    noMealsDesc: "Check back later for today's menu update.",
    postedToday: "Posted Today",
    syncingKitchen: "Syncing with school kitchen...",
    campusInfrastructure: "Campus Infrastructure",
    noFacilitiesTitle: "No facilities available",
    noFacilitiesDesc: "We are updating our gallery. Please check back later.",
    loadingGallery: "Loading facilities gallery...",
    studentExcellence: "Student Excellence",
    noStarsTitle: "No student stars posted yet",
    noStarsDesc: "We look forward to celebrating our students' achievements here.",
    loadingAchievements: "Loading achievements...",
    communityVoice: "Community Voice",
    shareThoughtsTitle: "Share Your Thoughts",
    shareThoughtsDesc: "We value your input. Direct communication with the administration helps us improve every day.",
    nameLabel: "Your Name (Optional)",
    namePlaceholder: "e.g. Priya (Class 5 Parent)",
    anonymousLabel: "Keep this feedback anonymous",
    messageLabel: "Your Message",
    messagePlaceholder: "Share your ideas, concerns, or suggestions...",
    submitBtn: "Submit to Administration",
    submittingBtn: "Sending securely...",
    recentConversations: "Recent Conversations",
    resolved: "Resolved",
    pending: "Pending Review",
    officialResponse: "Official Response",
    noFeedback: "Be the first to share your thoughts.",
    footerText: "Fostering transparency and excellence in education. A direct connection between our school and your home.",
    allRightsReserved: "All rights reserved.",
    toggleLang: "Switch to Kannada",
    sendAnnouncement: "Send Announcement",
    announcementTitle: "Announcement Title",
    announcementBody: "Full announcement text...",
    announcementType: "Announcement Type",
    priority: "Priority",
    category: "Category",
    author: "Author",
    sendNow: "Send Now",
    sending: "Sending...",
    typeText: "📝 Text Only",
    typeImage: "📷 Image",
    typeVideo: "🎬 Video",
    typeGif: "✨ GIF",
    typeDocument: "📄 Document (PDF/DOC)",
    typePromo: "📢 Promo Banner",
    priorityNormal: "🟢 Normal",
    priorityImportant: "🟡 Important",
    priorityUrgent: "🔴 Urgent",
    priorityInfo: "🔵 Info",
    navHome: "Home",
    navMeals: "Meals",
    navInfrastructure: "Infrastructure",
    navStars: "Student Stars",
    navFeedback: "Feedback",
    navNotices: "Notices",
    dashboardMeal: "Today's Meal",
    dashboardInfra: "Infrastructure",
    dashboardStars: "Student Stars",
    dashboardNotices: "Notices",
    dashboardTitle: "School Overview",
    dashboardSubtitle: "A quick look at today's meals, achievements, and notices.",
    dashMealSub: "Nutritious & Balanced",
    dashMealBadge: "Updated Today",
    dashMealDesc: "Rice, Sambar, Vegetable Curry, Curd",
    dashInfraSub: "Modern Facilities",
    dashInfraBadge: "Gallery",
    dashInfraDesc: "Explore our world-class campus facilities",
    dashStarsSub: "Hall of Fame",
    dashStarsBadge: "Leaderboard",
    dashStarsDesc: "Celebrating recent top achievers",
    dashNoticesSub: "Stay Updated",
    dashNoticesBadge: "Important",
    dashNoticesDesc: "Stay informed with the latest updates",
    portalFeatures: "Portal Features",
    featMeal: "View real-time meal updates",
    featInfra: "Browse infrastructure gallery",
    featStars: "See student achievements",
    featNotices: "Read notices & announcements",
    featFeedback: "Submit feedback & view replies",
    noticeTitle: "Official Circulars & Announcements",
    noticeSubtitle: "Stay updated with the latest notices directly from the school administration.",
    noNoticesYet: "No Announcements Yet",
    noNoticesDesc: "Check back later for updates from the administration.",
    footerQuickLinks: "Quick Links",
    footerContact: "Contact & Support",
    footerEmail: "Email",
    footerPhone: "Phone",
    footerAddress: "Address",
    dashCapTitle: "How to Use This Portal",
    dashCapHeading: "Simple updates for every parent.",
    dashCapDesc: "Everything you need to know about your child's day at school is listed here.",
    promoTitle1: "Stay Connected.",
    promoTitle2: "Stay Informed.",
    promoDesc: "Experience the future of parent-school communication. Everything you need to know about your child's day, right in your pocket.",
    promoBtn: "Back to Top",
    heroMeal: "Today's Meal",
    heroNotice: "Latest Notice",
    heroNoticeDesc: "PTM Meeting",
    heroFeedback: "Feedback",
    heroFeedbackDesc: "Resolved",
    heroExplore: "Explore Portal"
  },
  kn: {
    siteTitle: "ಶಾಲೆ-ನಮ್ಮ ಹೆಮ್ಮೆ",
    heroBadge: "ಅಧಿಕೃತ ಪೋಷಕರ ಪೋರ್ಟಲ್",
    heroTitle: "ಪ್ರತಿ ಪೋಷಕರಿಗಾಗಿ ಲೈವ್ ಶಾಲಾ ನವೀಕರಣಗಳು",
    heroSubtitle: "ನಿಮ್ಮ ಮಗುವಿನ ಶಾಲೆಯೊಂದಿಗೆ ಸುಲಭವಾಗಿ ಸಂಪರ್ಕದಲ್ಲಿರಿ. ಇಂದಿನ ಊಟ, ವಿದ್ಯಾರ್ಥಿಗಳ ಸಾಧನೆಗಳು ಮತ್ತು ಪ್ರಮುಖ ಸೂಚನೆಗಳನ್ನು ನೋಡಿ.",
    valTransparency: "ಪಾರದರ್ಶಕತೆ",
    valSafety: "ಸುರಕ್ಷತೆ",
    valAchievement: "ಸಾಧನೆ",
    valCommunication: "ಸಂವಹನ",
    dailyMealProgram: "ಇಂದಿನ ಶಾಲಾ ಊಟ",
    mealFeedSubtitle: "ನಿಮ್ಮ ಮಗು ಇಂದು ಶಾಲೆಯಲ್ಲಿ ಏನು ತಿನ್ನುತ್ತಿದೆ ಎಂಬುದನ್ನು ನೋಡಿ. ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಗೆ ತಾಜಾ ಮತ್ತು ಆರೋಗ್ಯಕರ ಆಹಾರವನ್ನು ನಾವು ಖಚಿತಪಡಿಸುತ್ತೇವೆ.",
    mealPrepTitle: "ಊಟವನ್ನು ನೀಡಲಾಗುತ್ತಿದೆ",
    mealPrepDesc: "ಇಂದಿನ ಊಟದ ಮಾಹಿತಿಯನ್ನು ನಾವು ಅಪ್‌ಡೇಟ್ ಮಾಡುವವರೆಗೆ ದಯವಿಟ್ಟು ಕಾಯಿರಿ.",
    todaySpecial: "ಇಂದಿನ ವಿಶೇಷ",
    pastRecord: "ಹಿಂದಿನ ದಾಖಲೆ",
    menuItems: "ಮೆನು ಐಟಂಗಳು",
    infraTitle: "ನಮ್ಮ ಸೌಲಭ್ಯಗಳು",
    infraSubtitle: "ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಾವು ಅತ್ಯಾಧುನಿಕ ಸೌಲಭ್ಯಗಳೊಂದಿಗೆ ಪೋಷಣೆಯ ವಾತಾವರಣವನ್ನು ಒದಗಿಸುತ್ತೇವೆ.",
    exploreGallery: "ಗ್ಯಾಲರಿ ಅನ್ವೇಷಿಸಿ",
    starsStageSet: "ವೇದಿಕೆ ಸಿದ್ಧವಾಗಿದೆ",
    starsStageDesc: "ನಮ್ಮ ಮೊದಲ ಹಂತದ ಉನ್ನತ ಸಾಧಕರನ್ನು ಆಚರಿಸಲು ನಾವು ಸಿದ್ಧರಾಗುತ್ತಿರುವಾಗ ಟ್ಯೂನ್ ಮಾಡಿ.",
    searchCirculars: "ಸುತ್ತೋಲೆಗಳನ್ನು ಹುಡುಕಿ...",
    filterAll: "ಎಲ್ಲಾ",
    filterUrgent: "ತುರ್ತು",
    filterImportant: "ಪ್ರಮುಖ",
    filterInfo: "ಮಾಹಿತಿ",
    viewUpdates: "ನವೀಕರಣಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    parentsPortal: "ಪೋಷಕರ ಪೋರ್ಟಲ್",
    adminOnline: "ಆಡಳಿತ ಆನ್‌ಲೈನ್",
    adminOffline: "ಆಡಳಿತ ಆಫ್‌ಲೈನ್",
    adminTyping: "ಆಡಳಿತವು ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಟೈಪ್ ಮಾಡುತ್ತಿದೆ...",
    liveSyncText: "ಲೈವ್ ಸಿಂಕ್",
    liveSyncActive: "ಲೈವ್ ಸಿಂಕ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    attachImage: "ಚಿತ್ರವನ್ನು ಲಗತ್ತಿಸಿ",
    midDayMeals: "ಮಧ್ಯಾಹ್ನದ ಬಿಸಿಯೂಟ",
    noMealsTitle: "ಇನ್ನೂ ಯಾವುದೇ ಊಟವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿಲ್ಲ",
    noMealsDesc: "ಇಂದಿನ ಮೆನು ನವೀಕರಣಕ್ಕಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ.",
    postedToday: "ಇಂದು ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ",
    syncingKitchen: "ಶಾಲೆಯ ಅಡುಗೆಮನೆಯೊಂದಿಗೆ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",
    campusInfrastructure: "ಕ್ಯಾಂಪಸ್ ಮೂಲಸೌಕರ್ಯ",
    noFacilitiesTitle: "ಯಾವುದೇ ಸೌಲಭ್ಯಗಳು ಲಭ್ಯವಿಲ್ಲ",
    noFacilitiesDesc: "ನಾವು ನಮ್ಮ ಗ್ಯಾಲರಿಯನ್ನು ನವೀಕರಿಸುತ್ತಿದ್ದೇವೆ. ದಯವಿಟ್ಟು ನಂತರ ಪರಿಶೀಲಿಸಿ.",
    loadingGallery: "ಗ್ಯಾಲರಿಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    studentExcellence: "ವಿದ್ಯಾರ್ಥಿ ಶ್ರೇಷ್ಠತೆ",
    noStarsTitle: "ಇನ್ನೂ ಯಾವುದೇ ವಿದ್ಯಾರ್ಥಿ ಸಾಧನೆಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿಲ್ಲ",
    noStarsDesc: "ನಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳ ಸಾಧನೆಗಳನ್ನು ಇಲ್ಲಿ ಆಚರಿಸಲು ನಾವು ಎದುರು ನೋಡುತ್ತಿದ್ದೇವೆ.",
    loadingAchievements: "ಸಾಧನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    communityVoice: "ಸಮುದಾಯದ ಧ್ವನಿ",
    shareThoughtsTitle: "ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
    shareThoughtsDesc: "ನಿಮ್ಮ ಅಭಿಪ್ರಾಯವನ್ನು ನಾವು ಗೌರವಿಸುತ್ತೇವೆ. ಆಡಳಿತದೊಂದಿಗೆ ನೇರ ಸಂವಹನವು ಪ್ರತಿದಿನ ನಮ್ಮನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    nameLabel: "ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    namePlaceholder: "ಉದಾ. ಪ್ರಿಯಾ (೫ನೇ ತರಗತಿ ಪೋಷಕರು)",
    anonymousLabel: "ಈ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಅನಾಮಧೇಯವಾಗಿರಿಸಿ",
    messageLabel: "ನಿಮ್ಮ ಸಂದೇಶ",
    messagePlaceholder: "ನಿಮ್ಮ ಆಲೋಚನೆಗಳು, ಕಾಳಜಿಗಳು ಅಥವಾ ಸಲಹೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...",
    submitBtn: "ಆಡಳಿತಕ್ಕೆ ಸಲ್ಲಿಸಿ",
    submittingBtn: "ಸುರಕ್ಷಿತವಾಗಿ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    recentConversations: "ಇತ್ತೀಚಿನ ಸಂಭಾಷಣೆಗಳು",
    resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    pending: "ಪರಿಶೀಲನೆ ಬಾಕಿಯಿದೆ",
    officialResponse: "ಅಧಿಕೃತ ಪ್ರತಿಕ್ರಿಯೆ",
    noFeedback: "ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳುವಲ್ಲಿ ಮೊದಲಿಗರಾಗಿರಿ.",
    footerText: "ಶಿಕ್ಷಣದಲ್ಲಿ ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಶ್ರೇಷ್ಠತೆಯನ್ನು ಬೆಳೆಸುವುದು. ನಮ್ಮ ಶಾಲೆ ಮತ್ತು ನಿಮ್ಮ ಮನೆಯ ನಡುವೆ ನೇರ ಸಂಪರ್ಕ.",
    allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    toggleLang: "Switch to English",
    sendAnnouncement: "ಪ್ರಕಟಣೆ ಕಳುಹಿಸಿ",
    announcementTitle: "ಪ್ರಕಟಣೆಯ ಶೀರ್ಷಿಕೆ",
    announcementBody: "ಪ್ರಕಟಣೆಯ ಸಂಪೂರ್ಣ ಪಠ್ಯ...",
    announcementType: "ಪ್ರಕಟಣೆಯ ಪ್ರಕಾರ",
    priority: "ಆದ್ಯತೆ",
    category: "ವರ್ಗ",
    author: "ಲೇಖಕರು",
    sendNow: "ಈಗ ಕಳುಹಿಸಿ",
    sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    typeText: "📝 ಕೇವಲ ಪಠ್ಯ",
    typeImage: "📷 ಚಿತ್ರ",
    typeVideo: "🎬 ವೀಡಿಯೊ",
    typeGif: "✨ GIF",
    typeDocument: "📄 ದಾಖಲೆ (PDF/DOC)",
    typePromo: "📢 ಪ್ರೋಮೋ ಬ್ಯಾನರ್",
    priorityNormal: "🟢 ಸಾಮಾನ್ಯ",
    priorityImportant: "🟡 ಪ್ರಮುಖ",
    priorityUrgent: "🔴 ತುರ್ತು",
    priorityInfo: "🔵 ಮಾಹಿತಿ",
    navHome: "ಮುಖಪುಟ",
    navMeals: "ಊಟ",
    navInfrastructure: "ಮೂಲಸೌಕರ್ಯ",
    navStars: "ವಿದ್ಯಾರ್ಥಿ ಸಾಧಕರು",
    navFeedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    navNotices: "ಸೂಚನೆಗಳು",
    dashboardMeal: "ಇಂದಿನ ಊಟ",
    dashboardInfra: "ಮೂಲಸೌಕರ್ಯ",
    dashboardStars: "ವಿದ್ಯಾರ್ಥಿ ಸಾಧಕರು",
    dashboardNotices: "ಸೂಚನೆಗಳು",
    dashboardTitle: "ಶಾಲೆಯ ಅವಲೋಕನ",
    dashboardSubtitle: "ಇಂದಿನ ಊಟ, ಸಾಧನೆಗಳು ಮತ್ತು ಸೂಚನೆಗಳ ಒಂದು ತ್ವರಿತ ನೋಟ.",
    dashMealSub: "ಪೌಷ್ಟಿಕ ಮತ್ತು ಸಮತೋಲಿತ",
    dashMealBadge: "ಇಂದು ನವೀಕರಿಸಲಾಗಿದೆ",
    dashMealDesc: "ಅನ್ನ, ಸಾಂಬಾರ್, ತರಕಾರಿ ಪಲ್ಯ, ಮೊಸರು",
    dashInfraSub: "ಆಧುನಿಕ ಸೌಲಭ್ಯಗಳು",
    dashInfraBadge: "ಗ್ಯಾಲರಿ",
    dashInfraDesc: "ನಮ್ಮ ವಿಶ್ವದರ್ಜೆಯ ಕ್ಯಾಂಪಸ್ ಸೌಲಭ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    dashStarsSub: "ಹಾಲ್ ಆಫ್ ಫೇಮ್",
    dashStarsBadge: "ಲೀಡರ್‌ಬೋರ್ಡ್",
    dashStarsDesc: "ಇತ್ತೀಚಿನ ಸಾಧಕರನ್ನು ಆಚರಿಸಲಾಗುತ್ತಿದೆ",
    dashNoticesSub: "ನವೀಕೃತವಾಗಿರಿ",
    dashNoticesBadge: "ಪ್ರಮುಖ",
    dashNoticesDesc: "ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳೊಂದಿಗೆ ಮಾಹಿತಿ ಪಡೆಯಿರಿ",
    portalFeatures: "ಪೋರ್ಟಲ್ ವೈಶಿಷ್ಟ್ಯಗಳು",
    featMeal: "ನೈಜ-ಸಮಯದ ಊಟದ ನವೀಕರಣಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    featInfra: "ಮೂಲಸೌಕರ್ಯ ಗ್ಯಾಲರಿಯನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    featStars: "ವಿದ್ಯಾರ್ಥಿಗಳ ಸಾಧನೆಗಳನ್ನು ನೋಡಿ",
    featNotices: "ಸೂಚನೆಗಳು ಮತ್ತು ಪ್ರಕಟಣೆಗಳನ್ನು ಓದಿ",
    featFeedback: "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಸಲ್ಲಿಸಿ ಮತ್ತು ಉತ್ತರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    noticeTitle: "ಅಧಿಕೃತ ಸುತ್ತೋಲೆಗಳು ಮತ್ತು ಪ್ರಕಟಣೆಗಳು",
    noticeSubtitle: "ಶಾಲಾ ಆಡಳಿತದಿಂದ ನೇರವಾಗಿ ಇತ್ತೀಚಿನ ಸೂಚನೆಗಳೊಂದಿಗೆ ನವೀಕೃತವಾಗಿರಿ.",
    noNoticesYet: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಕಟಣೆಗಳಿಲ್ಲ",
    noNoticesDesc: "ಆಡಳಿತದಿಂದ ನವೀಕರಣಗಳಿಗಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ.",
    footerQuickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    footerContact: "ಸಂಪರ್ಕ ಮತ್ತು ಬೆಂಬಲ",
    footerEmail: "ಇಮೇಲ್",
    footerPhone: "ಫೋನ್",
    footerAddress: "ವಿಳಾಸ",
    dashCapTitle: "ಈ ಪೋರ್ಟಲ್ ಅನ್ನು ಹೇಗೆ ಬಳಸುವುದು",
    dashCapHeading: "ಪ್ರತಿ ಪೋಷಕರಿಗೆ ಸರಳ ಅಪ್‌ಡೇಟ್‌ಗಳು.",
    dashCapDesc: "ಶಾಲೆಯಲ್ಲಿ ನಿಮ್ಮ ಮಗುವಿನ ದಿನದ ಬಗ್ಗೆ ನೀವು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದ ಎಲ್ಲವನ್ನೂ ಇಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ.",
    promoTitle1: "ಸಂಪರ್ಕದಲ್ಲಿರಿ.",
    promoTitle2: "ತಿಳಿದುಕೊಳ್ಳುತ್ತಿರಿ.",
    promoDesc: "ಪೋಷಕ-ಶಾಲಾ ಸಂವಹನದ ಭವಿಷ್ಯವನ್ನು ಅನುಭವಿಸಿ. ನಿಮ್ಮ ಮಗುವಿನ ದಿನದ ಬಗ್ಗೆ ನೀವು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದ ಎಲ್ಲವೂ ನಿಮ್ಮ ಜೇಬಿನಲ್ಲಿದೆ.",
    promoBtn: "ಮೇಲಕ್ಕೆ ಹೋಗಿ",
    heroMeal: "ಇಂದಿನ ಊಟ",
    heroNotice: "ಇತ್ತೀಚಿನ ಸೂಚನೆ",
    heroNoticeDesc: "ಪಿಟಿಎಂ ಸಭೆ",
    heroFeedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    heroFeedbackDesc: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    heroExplore: "ಪೋರ್ಟಲ್ ಅನ್ವೇಷಿಸಿ"
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('appLang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLang', lang);
    if (lang === 'kn') {
      document.documentElement.lang = 'kn';
    } else {
      document.documentElement.lang = 'en';
    }
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => prev === 'en' ? 'kn' : 'en');
  };

  const t = (key) => {
    if (!dictionary[lang]) return dictionary['en'][key] || key;
    return dictionary[lang][key] || dictionary['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
